### ISSUE TITLE
Blender 2.91 error

### ISSUE THREAD

**Issue by rodrigomenezesart** [kei-kabuto/blendgit#10]
error message when i try to enable the addon:
Traceback (most recent call last):
  File "/home/rodrigo/Applications/blender-2.91.0-linux64/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'blendgit-3'

**Comment by kei-kabuto** [comment]
Thank you for reporting error, @rodrigomenezesart!
And I updated latest release, adding new zip file unzippable as valid name(not include ".").
("blendgit-vX.X.X.zip" is to be imported as "blendgit" module)

**Comment by rodrigomenezesart** [comment]
Now worked, thank @kei-kabuto for the attention
